import type { SnippetTemplate } from '../types';

/**
 * SDK integration snippet templates for Razorpay
 * Based on Razorpay official documentation
 * 
 * Categories:
 * - SDK Setup (Checkout integration for different frameworks)
 * - Server Setup (Backend integration)
 */
export const sdkSnippetTemplates: SnippetTemplate[] = [
  // ============================================
  // WEB CHECKOUT - HTML/JavaScript
  // ============================================
  {
    id: 'sdk.checkout-html',
    name: 'Razorpay Checkout (HTML)',
    description: 'Standard Razorpay Checkout.js integration for HTML/JavaScript',
    category: 'sdk',
    language: ['html', 'javascript'],
    prefix: 'razorpay-checkout-html',
    body: [
      '<button id="rzp-button1">Pay Now</button>',
      '<script src="https://checkout.razorpay.com/v1/checkout.js"></script>',
      '<script>',
      'var options = {',
      '  key: "${1:YOUR_KEY_ID}",',
      '  amount: "${2:50000}",',
      '  currency: "${3:INR}",',
      '  name: "${4:Your Company Name}",',
      '  description: "${5:Test Transaction}",',
      '  image: "${6:https://example.com/logo.png}",',
      '  order_id: "${7:order_id_from_server}",',
      '  handler: function (response) {',
      '    alert("Payment ID: " + response.razorpay_payment_id);',
      '    alert("Order ID: " + response.razorpay_order_id);',
      '    alert("Signature: " + response.razorpay_signature);',
      '    // Send to server for verification',
      '  },',
      '  prefill: {',
      '    name: "${8:Customer Name}",',
      '    email: "${9:customer@example.com}",',
      '    contact: "${10:+919999999999}"',
      '  },',
      '  theme: {',
      '    color: "${11:#3399cc}"',
      '  }',
      '};',
      '',
      'var rzp = new Razorpay(options);',
      'document.getElementById("rzp-button1").onclick = function(e) {',
      '  rzp.open();',
      '  e.preventDefault();',
      '};',
      '</script>',
    ],
  },

  // ============================================
  // REACT CHECKOUT
  // ============================================
  {
    id: 'sdk.checkout-react',
    name: 'Razorpay Checkout (React)',
    description: 'Razorpay Checkout integration for React applications',
    category: 'sdk',
    language: ['typescriptreact', 'javascriptreact', 'typescript', 'javascript'],
    prefix: 'razorpay-checkout-react',
    body: [
      "import { useEffect } from 'react';",
      '',
      'declare global {',
      '  interface Window {',
      '    Razorpay: any;',
      '  }',
      '}',
      '',
      'export function useRazorpay() {',
      '  useEffect(() => {',
      "    const script = document.createElement('script');",
      "    script.src = 'https://checkout.razorpay.com/v1/checkout.js';",
      '    script.async = true;',
      '    document.body.appendChild(script);',
      '    return () => {',
      '      document.body.removeChild(script);',
      '    };',
      '  }, []);',
      '',
      '  const openPayment = (orderId: string, amount: number) => {',
      '    const options = {',
      '      key: "${1:YOUR_KEY_ID}",',
      '      amount: amount,',
      '      currency: "${2:INR}",',
      '      name: "${3:Your Company Name}",',
      '      description: "${4:Test Transaction}",',
      '      order_id: orderId,',
      '      handler: function (response: any) {',
      "        console.log('Payment ID:', response.razorpay_payment_id);",
      "        console.log('Order ID:', response.razorpay_order_id);",
      '        // Send to server for verification',
      '      },',
      '      prefill: {',
      '        name: "${5:Customer Name}",',
      '        email: "${6:customer@example.com}",',
      '        contact: "${7:+919999999999}"',
      '      },',
      '      theme: {',
      '        color: "${8:#3399cc}"',
      '      }',
      '    };',
      '',
      '    const rzp = new window.Razorpay(options);',
      '    rzp.open();',
      '  };',
      '',
      '  return { openPayment };',
      '}',
    ],
  },

  // ============================================
  // NEXT.JS CHECKOUT
  // ============================================
  {
    id: 'sdk.checkout-nextjs',
    name: 'Razorpay Checkout (Next.js)',
    description: 'Razorpay Checkout integration for Next.js applications',
    category: 'sdk',
    language: ['typescriptreact', 'javascriptreact', 'typescript', 'javascript'],
    prefix: 'razorpay-checkout-nextjs',
    body: [
      "'use client';",
      '',
      "import { useEffect, useState } from 'react';",
      '',
      'declare global {',
      '  interface Window {',
      '    Razorpay: any;',
      '  }',
      '}',
      '',
      'export default function PaymentButton() {',
      '  const [isLoaded, setIsLoaded] = useState(false);',
      '',
      '  useEffect(() => {',
      "    const script = document.createElement('script');",
      "    script.src = 'https://checkout.razorpay.com/v1/checkout.js';",
      '    script.async = true;',
      '    script.onload = () => setIsLoaded(true);',
      '    document.body.appendChild(script);',
      '    return () => {',
      '      if (document.body.contains(script)) {',
      '        document.body.removeChild(script);',
      '      }',
      '    };',
      '  }, []);',
      '',
      '  const handlePayment = async () => {',
      '    // Create order on server first',
      "    const res = await fetch('/api/create-order', {",
      "      method: 'POST',",
      "      headers: { 'Content-Type': 'application/json' },",
      '      body: JSON.stringify({ amount: ${1:50000} }),',
      '    });',
      '    const order = await res.json();',
      '',
      '    const options = {',
      '      key: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,',
      '      amount: order.amount,',
      '      currency: "${2:INR}",',
      '      name: "${3:Your Company Name}",',
      '      description: "${4:Test Transaction}",',
      '      order_id: order.id,',
      '      handler: async function (response: any) {',
      '        // Verify payment on server',
      "        await fetch('/api/verify-payment', {",
      "          method: 'POST',",
      "          headers: { 'Content-Type': 'application/json' },",
      '          body: JSON.stringify(response),',
      '        });',
      '      },',
      '      prefill: {',
      '        name: "${5:Customer Name}",',
      '        email: "${6:customer@example.com}",',
      '        contact: "${7:+919999999999}"',
      '      },',
      '      theme: {',
      '        color: "${8:#3399cc}"',
      '      }',
      '    };',
      '',
      '    const rzp = new window.Razorpay(options);',
      '    rzp.open();',
      '  };',
      '',
      '  return (',
      '    <button onClick={handlePayment} disabled={!isLoaded}>',
      '      Pay Now',
      '    </button>',
      '  );',
      '}',
    ],
  },

  // ============================================
  // VUE.JS CHECKOUT
  // ============================================
  {
    id: 'sdk.checkout-vue',
    name: 'Razorpay Checkout (Vue.js)',
    description: 'Razorpay Checkout integration for Vue.js applications',
    category: 'sdk',
    language: ['vue', 'javascript', 'typescript'],
    prefix: 'razorpay-checkout-vue',
    body: [
      '<template>',
      '  <button @click="handlePayment" :disabled="!isLoaded">Pay Now</button>',
      '</template>',
      '',
      '<script>',
      'export default {',
      "  name: 'PaymentButton',",
      '  data() {',
      '    return {',
      '      isLoaded: false',
      '    };',
      '  },',
      '  mounted() {',
      "    const script = document.createElement('script');",
      "    script.src = 'https://checkout.razorpay.com/v1/checkout.js';",
      '    script.async = true;',
      '    script.onload = () => { this.isLoaded = true; };',
      '    document.body.appendChild(script);',
      '  },',
      '  methods: {',
      '    handlePayment() {',
      '      const options = {',
      '        key: "${1:YOUR_KEY_ID}",',
      '        amount: ${2:50000},',
      '        currency: "${3:INR}",',
      '        name: "${4:Your Company Name}",',
      '        description: "${5:Test Transaction}",',
      '        order_id: "${6:order_id_from_server}",',
      '        handler: (response) => {',
      "          console.log('Payment ID:', response.razorpay_payment_id);",
      '          // Send to server for verification',
      '        },',
      '        prefill: {',
      '          name: "${7:Customer Name}",',
      '          email: "${8:customer@example.com}",',
      '          contact: "${9:+919999999999}"',
      '        },',
      '        theme: {',
      '          color: "${10:#3399cc}"',
      '        }',
      '      };',
      '',
      '      const rzp = new window.Razorpay(options);',
      '      rzp.open();',
      '    }',
      '  }',
      '};',
      '</script>',
    ],
  },

  // ============================================
  // ANGULAR CHECKOUT
  // ============================================
  {
    id: 'sdk.checkout-angular',
    name: 'Razorpay Checkout (Angular)',
    description: 'Razorpay Checkout integration for Angular applications',
    category: 'sdk',
    language: ['typescript'],
    prefix: 'razorpay-checkout-angular',
    body: [
      "import { Component, OnInit } from '@angular/core';",
      '',
      'declare var Razorpay: any;',
      '',
      '@Component({',
      "  selector: 'app-payment',",
      "  template: '<button (click)=\"handlePayment()\" [disabled]=\"!isLoaded\">Pay Now</button>'",
      '})',
      'export class PaymentComponent implements OnInit {',
      '  isLoaded = false;',
      '',
      '  ngOnInit() {',
      "    const script = document.createElement('script');",
      "    script.src = 'https://checkout.razorpay.com/v1/checkout.js';",
      '    script.async = true;',
      '    script.onload = () => { this.isLoaded = true; };',
      '    document.body.appendChild(script);',
      '  }',
      '',
      '  handlePayment() {',
      '    const options = {',
      '      key: "${1:YOUR_KEY_ID}",',
      '      amount: ${2:50000},',
      '      currency: "${3:INR}",',
      '      name: "${4:Your Company Name}",',
      '      description: "${5:Test Transaction}",',
      '      order_id: "${6:order_id_from_server}",',
      '      handler: (response: any) => {',
      "        console.log('Payment ID:', response.razorpay_payment_id);",
      '        // Send to server for verification',
      '      },',
      '      prefill: {',
      '        name: "${7:Customer Name}",',
      '        email: "${8:customer@example.com}",',
      '        contact: "${9:+919999999999}"',
      '      },',
      '      theme: {',
      '        color: "${10:#3399cc}"',
      '      }',
      '    };',
      '',
      '    const rzp = new Razorpay(options);',
      '    rzp.open();',
      '  }',
      '}',
    ],
  },

  // ============================================
  // NODE.JS SERVER
  // ============================================
  {
    id: 'sdk.server-node',
    name: 'Razorpay Server (Node.js)',
    description: 'Razorpay server-side integration for Node.js/Express',
    category: 'sdk',
    language: ['typescript', 'javascript'],
    prefix: 'razorpay-server-node',
    body: [
      "const Razorpay = require('razorpay');",
      "const crypto = require('crypto');",
      '',
      '// Initialize Razorpay',
      'const razorpay = new Razorpay({',
      '  key_id: process.env.RAZORPAY_KEY_ID,',
      '  key_secret: process.env.RAZORPAY_KEY_SECRET,',
      '});',
      '',
      '// Create Order',
      'async function createOrder(amount: number) {',
      '  const options = {',
      '    amount: amount, // Amount in paise',
      '    currency: "${1:INR}",',
      '    receipt: "${2:receipt_}" + Date.now(),',
      '  };',
      '  return await razorpay.orders.create(options);',
      '}',
      '',
      '// Verify Payment Signature',
      'function verifyPayment(orderId: string, paymentId: string, signature: string) {',
      "  const body = orderId + '|' + paymentId;",
      '  const expectedSignature = crypto',
      "    .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET!)",
      '    .update(body)',
      "    .digest('hex');",
      '  return expectedSignature === signature;',
      '}',
      '',
      '// Express Routes Example',
      "// app.post('/create-order', async (req, res) => {",
      '//   const order = await createOrder(req.body.amount);',
      '//   res.json(order);',
      '// });',
      '',
      "// app.post('/verify-payment', (req, res) => {",
      '//   const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;',
      '//   const isValid = verifyPayment(razorpay_order_id, razorpay_payment_id, razorpay_signature);',
      '//   res.json({ success: isValid });',
      '// });',
    ],
  },

  // ============================================
  // PYTHON SERVER
  // ============================================
  {
    id: 'sdk.server-python',
    name: 'Razorpay Server (Python)',
    description: 'Razorpay server-side integration for Python/Flask',
    category: 'sdk',
    language: ['python'],
    prefix: 'razorpay-server-python',
    body: [
      'import razorpay',
      'import hmac',
      'import hashlib',
      'import os',
      '',
      '# Initialize Razorpay',
      'razorpay_client = razorpay.Client(',
      "    auth=(os.getenv('RAZORPAY_KEY_ID'), os.getenv('RAZORPAY_KEY_SECRET'))",
      ')',
      '',
      '# Create Order',
      'def create_order(amount):',
      '    """',
      '    Create a Razorpay order',
      '    :param amount: Amount in paise',
      '    """',
      '    order_data = {',
      '        "amount": amount,',
      '        "currency": "${1:INR}",',
      '        "receipt": f"receipt_{int(time.time())}"',
      '    }',
      '    return razorpay_client.order.create(data=order_data)',
      '',
      '# Verify Payment Signature',
      'def verify_payment(order_id, payment_id, signature):',
      '    """',
      '    Verify Razorpay payment signature',
      '    """',
      "    body = order_id + '|' + payment_id",
      '    expected_signature = hmac.new(',
      "        os.getenv('RAZORPAY_KEY_SECRET').encode(),",
      '        body.encode(),',
      '        hashlib.sha256',
      '    ).hexdigest()',
      '    return expected_signature == signature',
      '',
      '# Flask Routes Example',
      "# @app.route('/create-order', methods=['POST'])",
      '# def create_order_route():',
      "#     amount = request.json.get('amount')",
      '#     order = create_order(amount)',
      '#     return jsonify(order)',
      '',
      "# @app.route('/verify-payment', methods=['POST'])",
      '# def verify_payment_route():',
      "#     order_id = request.json.get('razorpay_order_id')",
      "#     payment_id = request.json.get('razorpay_payment_id')",
      "#     signature = request.json.get('razorpay_signature')",
      '#     is_valid = verify_payment(order_id, payment_id, signature)',
      "#     return jsonify({'success': is_valid})",
    ],
  },

  // ============================================
  // JAVA SERVER
  // ============================================
  {
    id: 'sdk.server-java',
    name: 'Razorpay Server (Java)',
    description: 'Razorpay server-side integration for Java',
    category: 'sdk',
    language: ['java'],
    prefix: 'razorpay-server-java',
    body: [
      'import com.razorpay.RazorpayClient;',
      'import com.razorpay.Order;',
      'import com.razorpay.RazorpayException;',
      'import org.json.JSONObject;',
      'import javax.crypto.Mac;',
      'import javax.crypto.spec.SecretKeySpec;',
      '',
      'public class RazorpayService {',
      '    private RazorpayClient razorpay;',
      '    private String keySecret;',
      '',
      '    public RazorpayService() throws RazorpayException {',
      '        String keyId = System.getenv("RAZORPAY_KEY_ID");',
      '        this.keySecret = System.getenv("RAZORPAY_KEY_SECRET");',
      '        this.razorpay = new RazorpayClient(keyId, keySecret);',
      '    }',
      '',
      '    // Create Order',
      '    public Order createOrder(int amount) throws RazorpayException {',
      '        JSONObject orderRequest = new JSONObject();',
      '        orderRequest.put("amount", amount); // Amount in paise',
      '        orderRequest.put("currency", "${1:INR}");',
      '        orderRequest.put("receipt", "receipt_" + System.currentTimeMillis());',
      '        return razorpay.orders.create(orderRequest);',
      '    }',
      '',
      '    // Verify Payment Signature',
      '    public boolean verifyPayment(String orderId, String paymentId, String signature) {',
      '        try {',
      '            String body = orderId + "|" + paymentId;',
      '            Mac mac = Mac.getInstance("HmacSHA256");',
      '            SecretKeySpec secretKey = new SecretKeySpec(keySecret.getBytes(), "HmacSHA256");',
      '            mac.init(secretKey);',
      '            byte[] hash = mac.doFinal(body.getBytes());',
      '            StringBuilder hexString = new StringBuilder();',
      '            for (byte b : hash) {',
      '                String hex = Integer.toHexString(0xff & b);',
      '                if (hex.length() == 1) hexString.append("0");',
      '                hexString.append(hex);',
      '            }',
      '            return hexString.toString().equals(signature);',
      '        } catch (Exception e) {',
      '            return false;',
      '        }',
      '    }',
      '}',
    ],
  },

  // ============================================
  // GO SERVER
  // ============================================
  {
    id: 'sdk.server-go',
    name: 'Razorpay Server (Go)',
    description: 'Razorpay server-side integration for Go',
    category: 'sdk',
    language: ['go'],
    prefix: 'razorpay-server-go',
    body: [
      'package main',
      '',
      'import (',
      '    "crypto/hmac"',
      '    "crypto/sha256"',
      '    "encoding/hex"',
      '    "fmt"',
      '    "os"',
      '    "time"',
      '',
      '    razorpay "github.com/razorpay/razorpay-go"',
      ')',
      '',
      'var client *razorpay.Client',
      '',
      'func init() {',
      '    keyID := os.Getenv("RAZORPAY_KEY_ID")',
      '    keySecret := os.Getenv("RAZORPAY_KEY_SECRET")',
      '    client = razorpay.NewClient(keyID, keySecret)',
      '}',
      '',
      '// CreateOrder creates a Razorpay order',
      'func CreateOrder(amount int) (map[string]interface{}, error) {',
      '    data := map[string]interface{}{',
      '        "amount":   amount, // Amount in paise',
      '        "currency": "${1:INR}",',
      '        "receipt":  fmt.Sprintf("receipt_%d", time.Now().Unix()),',
      '    }',
      '    return client.Order.Create(data, nil)',
      '}',
      '',
      '// VerifyPayment verifies the Razorpay payment signature',
      'func VerifyPayment(orderID, paymentID, signature string) bool {',
      '    keySecret := os.Getenv("RAZORPAY_KEY_SECRET")',
      '    body := orderID + "|" + paymentID',
      '',
      '    mac := hmac.New(sha256.New, []byte(keySecret))',
      '    mac.Write([]byte(body))',
      '    expectedSignature := hex.EncodeToString(mac.Sum(nil))',
      '',
      '    return expectedSignature == signature',
      '}',
    ],
  },

  // ============================================
  // RUBY SERVER
  // ============================================
  {
    id: 'sdk.server-ruby',
    name: 'Razorpay Server (Ruby)',
    description: 'Razorpay server-side integration for Ruby',
    category: 'sdk',
    language: ['ruby'],
    prefix: 'razorpay-server-ruby',
    body: [
      "require 'razorpay'",
      "require 'openssl'",
      '',
      '# Initialize Razorpay',
      'Razorpay.setup(ENV["RAZORPAY_KEY_ID"], ENV["RAZORPAY_KEY_SECRET"])',
      '',
      '# Create Order',
      'def create_order(amount)',
      '  order_params = {',
      '    amount: amount, # Amount in paise',
      '    currency: "${1:INR}",',
      '    receipt: "receipt_#{Time.now.to_i}"',
      '  }',
      '  Razorpay::Order.create(order_params)',
      'end',
      '',
      '# Verify Payment Signature',
      'def verify_payment(order_id, payment_id, signature)',
      '  body = "#{order_id}|#{payment_id}"',
      '  expected_signature = OpenSSL::HMAC.hexdigest(',
      '    OpenSSL::Digest.new("sha256"),',
      '    ENV["RAZORPAY_KEY_SECRET"],',
      '    body',
      '  )',
      '  expected_signature == signature',
      'end',
      '',
      '# Rails/Sinatra Routes Example',
      "# post '/create-order' do",
      '#   amount = params[:amount]',
      '#   order = create_order(amount)',
      '#   order.to_json',
      '# end',
      '',
      "# post '/verify-payment' do",
      '#   is_valid = verify_payment(',
      '#     params[:razorpay_order_id],',
      '#     params[:razorpay_payment_id],',
      '#     params[:razorpay_signature]',
      '#   )',
      '#   { success: is_valid }.to_json',
      '# end',
    ],
  },

  // ============================================
  // PHP SERVER
  // ============================================
  {
    id: 'sdk.server-php',
    name: 'Razorpay Server (PHP)',
    description: 'Razorpay server-side integration for PHP',
    category: 'sdk',
    language: ['php'],
    prefix: 'razorpay-server-php',
    body: [
      '<?php',
      "require 'vendor/autoload.php';",
      '',
      'use Razorpay\\Api\\Api;',
      '',
      '// Initialize Razorpay',
      "$keyId = getenv('RAZORPAY_KEY_ID');",
      "$keySecret = getenv('RAZORPAY_KEY_SECRET');",
      '$api = new Api($keyId, $keySecret);',
      '',
      '// Create Order',
      'function createOrder($api, $amount) {',
      '    $orderData = [',
      "        'receipt' => 'receipt_' . time(),",
      "        'amount' => $amount, // Amount in paise",
      "        'currency' => '${1:INR}'",
      '    ];',
      '    return $api->order->create($orderData);',
      '}',
      '',
      '// Verify Payment Signature',
      'function verifyPayment($orderId, $paymentId, $signature) {',
      "    $keySecret = getenv('RAZORPAY_KEY_SECRET');",
      "    $body = $orderId . '|' . $paymentId;",
      "    $expectedSignature = hash_hmac('sha256', $body, $keySecret);",
      '    return $expectedSignature === $signature;',
      '}',
      '',
      '// Usage Example',
      "// if ($_SERVER['REQUEST_METHOD'] === 'POST') {",
      "//     if ($_SERVER['REQUEST_URI'] === '/create-order') {",
      "//         $amount = json_decode(file_get_contents('php://input'), true)['amount'];",
      '//         $order = createOrder($api, $amount);',
      "//         header('Content-Type: application/json');",
      '//         echo json_encode($order->toArray());',
      '//     }',
      '// }',
      '?>',
    ],
  },

  // ============================================
  // ANDROID (KOTLIN)
  // ============================================
  {
    id: 'sdk.checkout-android',
    name: 'Razorpay Checkout (Android/Kotlin)',
    description: 'Razorpay Checkout integration for Android (Kotlin)',
    category: 'sdk',
    language: ['kotlin'],
    prefix: 'razorpay-checkout-android',
    body: [
      'import com.razorpay.Checkout',
      'import com.razorpay.PaymentResultListener',
      'import org.json.JSONObject',
      '',
      'class PaymentActivity : AppCompatActivity(), PaymentResultListener {',
      '',
      '    override fun onCreate(savedInstanceState: Bundle?) {',
      '        super.onCreate(savedInstanceState)',
      '        Checkout.preload(applicationContext)',
      '    }',
      '',
      '    fun startPayment(orderId: String, amount: Int) {',
      '        val checkout = Checkout()',
      '        checkout.setKeyID("${1:YOUR_KEY_ID}")',
      '',
      '        try {',
      '            val options = JSONObject().apply {',
      '                put("name", "${2:Your Company Name}")',
      '                put("description", "${3:Test Transaction}")',
      '                put("order_id", orderId)',
      '                put("currency", "${4:INR}")',
      '                put("amount", amount) // Amount in paise',
      '                put("prefill", JSONObject().apply {',
      '                    put("email", "${5:customer@example.com}")',
      '                    put("contact", "${6:+919999999999}")',
      '                })',
      '                put("theme", JSONObject().apply {',
      '                    put("color", "${7:#3399cc}")',
      '                })',
      '            }',
      '            checkout.open(this, options)',
      '        } catch (e: Exception) {',
      '            Toast.makeText(this, "Error: ${e.message}", Toast.LENGTH_LONG).show()',
      '        }',
      '    }',
      '',
      '    override fun onPaymentSuccess(razorpayPaymentId: String?) {',
      '        Toast.makeText(this, "Payment successful: $razorpayPaymentId", Toast.LENGTH_LONG).show()',
      '        // Send to server for verification',
      '    }',
      '',
      '    override fun onPaymentError(code: Int, response: String?) {',
      '        Toast.makeText(this, "Payment failed: $response", Toast.LENGTH_LONG).show()',
      '    }',
      '}',
    ],
  },

  // ============================================
  // iOS (SWIFT)
  // ============================================
  {
    id: 'sdk.checkout-ios',
    name: 'Razorpay Checkout (iOS/Swift)',
    description: 'Razorpay Checkout integration for iOS (Swift)',
    category: 'sdk',
    language: ['swift'],
    prefix: 'razorpay-checkout-ios',
    body: [
      'import UIKit',
      'import Razorpay',
      '',
      'class PaymentViewController: UIViewController, RazorpayPaymentCompletionProtocol {',
      '',
      '    var razorpay: RazorpayCheckout!',
      '',
      '    override func viewDidLoad() {',
      '        super.viewDidLoad()',
      '        razorpay = RazorpayCheckout.initWithKey("${1:YOUR_KEY_ID}", andDelegate: self)',
      '    }',
      '',
      '    func startPayment(orderId: String, amount: Int) {',
      '        let options: [String: Any] = [',
      '            "amount": amount, // Amount in paise',
      '            "currency": "${2:INR}",',
      '            "name": "${3:Your Company Name}",',
      '            "description": "${4:Test Transaction}",',
      '            "order_id": orderId,',
      '            "prefill": [',
      '                "email": "${5:customer@example.com}",',
      '                "contact": "${6:+919999999999}"',
      '            ],',
      '            "theme": [',
      '                "color": "${7:#3399cc}"',
      '            ]',
      '        ]',
      '',
      '        razorpay.open(options)',
      '    }',
      '',
      '    func onPaymentSuccess(_ payment_id: String, andData response: [String: Any]?) {',
      '        print("Payment successful: \\(payment_id)")',
      '        // Send to server for verification',
      '    }',
      '',
      '    func onPaymentError(_ code: Int, description str: String, andData response: [String: Any]?) {',
      '        print("Payment failed: \\(str)")',
      '    }',
      '}',
    ],
  },

  // ============================================
  // FLUTTER (DART)
  // ============================================
  {
    id: 'sdk.checkout-flutter',
    name: 'Razorpay Checkout (Flutter)',
    description: 'Razorpay Checkout integration for Flutter',
    category: 'sdk',
    language: ['dart'],
    prefix: 'razorpay-checkout-flutter',
    body: [
      "import 'package:flutter/material.dart';",
      "import 'package:razorpay_flutter/razorpay_flutter.dart';",
      '',
      'class PaymentPage extends StatefulWidget {',
      '  @override',
      '  _PaymentPageState createState() => _PaymentPageState();',
      '}',
      '',
      'class _PaymentPageState extends State<PaymentPage> {',
      '  late Razorpay _razorpay;',
      '',
      '  @override',
      '  void initState() {',
      '    super.initState();',
      '    _razorpay = Razorpay();',
      '    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);',
      '    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);',
      '    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);',
      '  }',
      '',
      '  @override',
      '  void dispose() {',
      '    super.dispose();',
      '    _razorpay.clear();',
      '  }',
      '',
      '  void openCheckout(String orderId, int amount) {',
      '    var options = {',
      "      'key': '${1:YOUR_KEY_ID}',",
      "      'amount': amount, // Amount in paise",
      "      'currency': '${2:INR}',",
      "      'name': '${3:Your Company Name}',",
      "      'description': '${4:Test Transaction}',",
      "      'order_id': orderId,",
      "      'prefill': {",
      "        'contact': '${5:+919999999999}',",
      "        'email': '${6:customer@example.com}'",
      '      },',
      "      'theme': {",
      "        'color': '${7:#3399cc}'",
      '      }',
      '    };',
      '',
      '    try {',
      '      _razorpay.open(options);',
      '    } catch (e) {',
      "      debugPrint('Error: \\$e');",
      '    }',
      '  }',
      '',
      '  void _handlePaymentSuccess(PaymentSuccessResponse response) {',
      "    print('Payment successful: \\${response.paymentId}');",
      '    // Send to server for verification',
      '  }',
      '',
      '  void _handlePaymentError(PaymentFailureResponse response) {',
      "    print('Payment failed: \\${response.message}');",
      '  }',
      '',
      '  void _handleExternalWallet(ExternalWalletResponse response) {',
      "    print('External wallet: \\${response.walletName}');",
      '  }',
      '',
      '  @override',
      '  Widget build(BuildContext context) {',
      '    return Scaffold(',
      "      appBar: AppBar(title: Text('Payment')),",
      '      body: Center(',
      '        child: ElevatedButton(',
      "          onPressed: () => openCheckout('order_id', 50000),",
      "          child: Text('Pay Now'),",
      '        ),',
      '      ),',
      '    );',
      '  }',
      '}',
    ],
  },

  // ============================================
  // REACT NATIVE
  // ============================================
  {
    id: 'sdk.checkout-reactnative',
    name: 'Razorpay Checkout (React Native)',
    description: 'Razorpay Checkout integration for React Native',
    category: 'sdk',
    language: ['typescriptreact', 'javascriptreact', 'typescript', 'javascript'],
    prefix: 'razorpay-checkout-reactnative',
    body: [
      "import React from 'react';",
      "import { View, Button, Alert } from 'react-native';",
      "import RazorpayCheckout from 'react-native-razorpay';",
      '',
      'export default function PaymentScreen() {',
      '  const handlePayment = (orderId: string, amount: number) => {',
      '    const options = {',
      '      key: "${1:YOUR_KEY_ID}",',
      '      amount: amount, // Amount in paise',
      '      currency: "${2:INR}",',
      '      name: "${3:Your Company Name}",',
      '      description: "${4:Test Transaction}",',
      '      order_id: orderId,',
      '      prefill: {',
      '        email: "${5:customer@example.com}",',
      '        contact: "${6:+919999999999}",',
      '        name: "${7:Customer Name}"',
      '      },',
      '      theme: {',
      '        color: "${8:#3399cc}"',
      '      }',
      '    };',
      '',
      '    RazorpayCheckout.open(options)',
      '      .then((data: any) => {',
      "        Alert.alert('Success', `Payment ID: ${data.razorpay_payment_id}`);",
      '        // Send to server for verification',
      '      })',
      '      .catch((error: any) => {',
      "        Alert.alert('Error', error.description);",
      '      });',
      '  };',
      '',
      '  return (',
      '    <View>',
      '      <Button',
      '        title="Pay Now"',
      "        onPress={() => handlePayment('order_id', 50000)}",
      '      />',
      '    </View>',
      '  );',
      '}',
    ],
  },
];
